/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | Post | Author | Category | Slug | BlockContent | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: PORTFOLIO_QUERY
// Query: *[_type == 'portfolio'][0] {	title,	name,	professionalTitle,	projects[]->{		_id,		title,		"imageObject": {			image,			"lqip": image.asset->metadata.lqip,		},		date,		description,		short_description,		"liveDemoLink": links.liveDemo,		"gitHubLink": links.github,		techStack	},	"frontendTech": skills.frontendTech,	"backendTech": skills.backendTech,	"tools": skills.tools,	"hostingPlatforms": skills.hostingPlatforms,	"animationLibraries": skills.animationLibraries,	"design": skills.design,	"methodologies": skills.methodologies,	links}
export type PORTFOLIO_QUERYResult = null;
// Variable: METADATA_QUERY
// Query: *[_type == 'portfolio'][0] {	metadata {		seoTitle,		seoDescription,		seoKeywords,		seoImage,	},	links}
export type METADATA_QUERYResult = null;
// Variable: CONTACT_QUERY
// Query: *[_type == 'contact'][0] {	_id,	title,	titleLocation,	"lat": location.lat,	"lng": location.lng,	mapStyle,	links	}
export type CONTACT_QUERYResult = null;
// Variable: ABOUT_QUERY
// Query: *[_type == 'about'][0] {	_id,	title,	name,	magazineComponents[]{		// Image object		_type == "imageObject" => {			_key,			_type,			"imageObject": {				image,				"lqip": image.asset->metadata.lqip,			},			size,			hoverElement,			hoverText		},  		// Promoblock object		_type == "promoBlockMagazineObject" => {			_key,			_type,			title,			sectionTitle,			"imageObject": {				image,				"lqip": image.asset->metadata.lqip,			},			size,			text		},  		// Text object		_type == "textMagazineObject" => {			_key,			_type,			sectionTitle,			text,			size,			theme		},  		// Map object		_type == "mapMagazineObject" => {			_key,			_type,			mapStyle,			location		},	},	promoBlock{		title,		text,		layout,		background,		button{				textButton,			link		},		"imageObject": {			image,			"lqip": image.asset->metadata.lqip,		},		"imageUrl": image.asset->url,		"imageAlt": image.attribution	  	},	phone,	email,	links,	cv,	location}
export type ABOUT_QUERYResult = null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'portfolio'][0] {\n\ttitle,\n\tname,\n\tprofessionalTitle,\n\tprojects[]->{\n\t\t_id,\n\t\ttitle,\n\t\t\"imageObject\": {\n\t\t\timage,\n\t\t\t\"lqip\": image.asset->metadata.lqip,\n\t\t},\n\t\tdate,\n\t\tdescription,\n\t\tshort_description,\n\t\t\"liveDemoLink\": links.liveDemo,\n\t\t\"gitHubLink\": links.github,\n\t\ttechStack\n\t},\n\t\"frontendTech\": skills.frontendTech,\n\t\"backendTech\": skills.backendTech,\n\t\"tools\": skills.tools,\n\t\"hostingPlatforms\": skills.hostingPlatforms,\n\t\"animationLibraries\": skills.animationLibraries,\n\t\"design\": skills.design,\n\t\"methodologies\": skills.methodologies,\n\tlinks\n}": PORTFOLIO_QUERYResult;
    "*[_type == 'portfolio'][0] {\n\tmetadata {\n\t\tseoTitle,\n\t\tseoDescription,\n\t\tseoKeywords,\n\t\tseoImage,\n\t},\n\tlinks\n}": METADATA_QUERYResult;
    "*[_type == 'contact'][0] {\n\t_id,\n\ttitle,\n\ttitleLocation,\n\t\"lat\": location.lat,\n\t\"lng\": location.lng,\n\tmapStyle,\n\tlinks\t\n}": CONTACT_QUERYResult;
    "*[_type == 'about'][0] {\n\t_id,\n\ttitle,\n\tname,\n\tmagazineComponents[]{\n\t\t// Image object\n\t\t_type == \"imageObject\" => {\n\t\t\t_key,\n\t\t\t_type,\n\t\t\t\"imageObject\": {\n\t\t\t\timage,\n\t\t\t\t\"lqip\": image.asset->metadata.lqip,\n\t\t\t},\n\t\t\tsize,\n\t\t\thoverElement,\n\t\t\thoverText\n\t\t},\n  \n\t\t// Promoblock object\n\t\t_type == \"promoBlockMagazineObject\" => {\n\t\t\t_key,\n\t\t\t_type,\n\t\t\ttitle,\n\t\t\tsectionTitle,\n\t\t\t\"imageObject\": {\n\t\t\t\timage,\n\t\t\t\t\"lqip\": image.asset->metadata.lqip,\n\t\t\t},\n\t\t\tsize,\n\t\t\ttext\n\t\t},\n  \n\t\t// Text object\n\t\t_type == \"textMagazineObject\" => {\n\t\t\t_key,\n\t\t\t_type,\n\t\t\tsectionTitle,\n\t\t\ttext,\n\t\t\tsize,\n\t\t\ttheme\n\t\t},\n  \n\t\t// Map object\n\t\t_type == \"mapMagazineObject\" => {\n\t\t\t_key,\n\t\t\t_type,\n\t\t\tmapStyle,\n\t\t\tlocation\n\t\t},\n\t},\n\tpromoBlock{\n\t\ttitle,\n\t\ttext,\n\t\tlayout,\n\t\tbackground,\n\t\tbutton{\t\n\t\t\ttextButton,\n\t\t\tlink\n\t\t},\n\t\t\"imageObject\": {\n\t\t\timage,\n\t\t\t\"lqip\": image.asset->metadata.lqip,\n\t\t},\n\t\t\"imageUrl\": image.asset->url,\n\t\t\"imageAlt\": image.attribution\t  \n\t},\n\tphone,\n\temail,\n\tlinks,\n\tcv,\n\tlocation\n}": ABOUT_QUERYResult;
  }
}
